apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: 2-demon
  namespace: kub-6
  labels:
    app: multitool
spec:
  selector:
    matchLabels:
      name: dep-2
  template:
    metadata:
      labels:
        name: dep-2
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - name: logdir
          mountPath: /nodes-logs/syslog
          subPath: syslog
        - name: varlog
          mountPath: /var/log/syslog
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: logdir
        hostPath:
          path: /var/log
      - name: varlog
        hostPath:
          path: /var/log